### ISSUE TITLE
为什么要远程工作

### ISSUE THREAD

**Issue by lurongkai** [telework-club/website#3]

**Comment by nanhapy** [comment]
为什么要远程工作？

这种朝九晚五，走进写字楼办公的工作模式是从什么时候形成的，已经无从考证。但毫无争议的是，它已经成了我们对“工作”的固有观念。

对于上班族的我们，也都不免有过衣着光鲜，出入高楼大厦的憧憬。可是当我们真的成为了在办公室工作的一员，事情远没有想象那么简单。

面对通勤我们身心俱疲

对于需要去办公室上班的我们来说，工作日的一天大概是这样度过的：早上，闹钟一再催促。我们从梦中惊醒，对昨晚的晚睡懊悔不已。随即，我们不得不做出权衡：如果选择立刻起床，那么我们还有机会为自己或者家人准备一份早餐；如果选择再眯10分钟，那么我们只能选择在路边买份早点；如果已经眯了10分钟却还没醒来，那么早点可能就此泡汤。然后我们去坐地铁或者公交，毅然决然的闯进沙丁鱼罐头般的车厢。在漫长的行程过后，我们终于到达了办公室。新的一天才开始，却已经头昏脑胀。那么选择开车？拥堵的交通，难寻的车位，我们可能刚刚开出家门，就已经后悔。当我们终于停好了车，最后的一点耐性也消磨殆尽……

面对生活我们亏欠太多

中午我们对着订餐软件滑了五分钟，仍然不知道吃什么。那些精美塑料盒子装着的快餐，早已提不起我们的兴趣。闭眼点一个，草草了事。在令人讨厌的通勤的折磨下，我们起得更早，回来的更晚，我们可能会放弃健身活动，可能会错过和家人朋友的沟通，可能会错过哄孩子入睡的机会，可能会放弃自己充电学习的时间。我们把所有家事杂事堆到周末，可能我们会发现周末甚至比工作日还累…… 

面对朝九晚五和大都市我们想要逃离

我们每个人都有不同的生活需求，有的喜欢早起，有的喜欢晚睡，有的要照顾家人孩子，有的喜欢诗和远方。严格统一的上下班时间不仅会造成交通压力，也可能让我们错过自己最舒适高效的工作时间。而大都市，那个曾经梦寐以求的地方，现在可能变成了束缚住我们，让我们无法逃脱的围城。大都市用工作岗位锁住我们，但同时交通，房价，户口等等现实问题压的我们透不过气。

对于企业来说，拥有一座气派的办公大楼或者人性舒适的办公环境自然是实力的象征，是笼络人才的必要条件。那么在这个背后有什么不那么令人愉快的问题吗？

运营成本
也需要支付房租，电费，水费，物业费，办公耗材等等费用来支撑办公室的运转。

优势
  1. 对于企业：降低运营成本，房租/水电/网络/零食
  2. 对于客户：降低人力成本，美国企业雇佣中印员工/北京企业雇佣天津员工
  3. 对于员工：降低通勤成本，时间/交通费

时机成熟
1. 环境改变：人性化，加班996，福报；知识付费
2. 从业者素质提升：
3. 基础设施。从来没有哪个时代能像今天一样，如此便捷地在任何时间跟任 何地方的人沟通、协作。可是，还有一个基本的、人类自身的问题没有解决：还没 有升级换代的，是人们的思想。
4. 工作规范
